version: '3.1'

services:

  origin_stag:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_ecommerce_db
    links:
      - mysql:mysql

  mysql:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wp_ecommerce_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8000:3306"
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql